"""DefMon Detection Engine — stateful multi-mode detection for security events.

Modes:
1. Rule-based: Compiled regex patterns from config.yaml for SQLi, XSS, traversal.
2. Threshold: Sliding-window counters per IP for brute-force and scanning.
3. Behavioral: Per-IP rolling baseline with anomaly multiplier.

All thresholds, patterns, and weights are loaded from config.yaml.
Zero hardcoded values.

Complexity: O(r) per event where r is the number of detection rules.
"""

import asyncio
import re
import time
import uuid
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Optional

from loguru import logger

from defmon.config import get_settings
from defmon.parser import LogEvent


# ---------------------------------------------------------------------------
# Alert Dataclass
# ---------------------------------------------------------------------------
@dataclass
class Alert:
    """Security alert generated by the detection engine.

    Contains all context needed for SOAR playbook dispatch and dashboard display.
    """

    alert_id: str
    timestamp: datetime
    ip: str
    rule_id: str
    severity: str  # Critical / High / Medium / Low
    description: str
    raw_event: str
    risk_score: float
    tags: list[str] = field(default_factory=list)
    username: Optional[str] = None

    def to_dict(self) -> dict:
        """Serialize alert to dictionary for JSON output."""
        data = asdict(self)
        data["timestamp"] = self.timestamp.isoformat()
        return data


# ---------------------------------------------------------------------------
# Sliding Window Counter
# ---------------------------------------------------------------------------
class _SlidingWindowCounter:
    """Time-windowed counter for threshold-based detection.

    Tracks event timestamps per key within a configurable window.
    Automatically evicts expired entries on each access.
    """

    def __init__(self, window_seconds: int):
        """Initialize with the given time window.

        Args:
            window_seconds: Size of the sliding window in seconds.
        """
        self._window = window_seconds
        self._events: dict[str, list[float]] = defaultdict(list)

    def record(self, key: str, ts: Optional[float] = None) -> int:
        """Record an event and return the count within the current window.

        Args:
            key: Grouping key (e.g., IP address).
            ts: Event timestamp as Unix epoch. Defaults to now.

        Returns:
            Number of events for this key within the sliding window.
        """
        now = ts or time.time()
        cutoff = now - self._window

        # Evict expired entries
        self._events[key] = [t for t in self._events[key] if t > cutoff]

        # Record new event
        self._events[key].append(now)

        return len(self._events[key])

    def get_count(self, key: str) -> int:
        """Get current count for a key without recording a new event.

        Args:
            key: Grouping key to query.

        Returns:
            Current event count within the window.
        """
        now = time.time()
        cutoff = now - self._window
        self._events[key] = [t for t in self._events[key] if t > cutoff]
        return len(self._events[key])

    def reset(self) -> None:
        """Clear all tracked events."""
        self._events.clear()


# ---------------------------------------------------------------------------
# Behavioral Baseline Tracker
# ---------------------------------------------------------------------------
class _BehavioralBaseline:
    """Per-IP rolling baseline for behavioral anomaly detection.

    Maintains a rolling average of requests per minute for each IP.
    Flags anomalies when the current rate exceeds baseline × multiplier.
    """

    def __init__(
        self,
        baseline_window_minutes: int = 60,
        anomaly_multiplier: float = 3.0,
        min_samples: int = 10,
    ):
        """Initialize behavioral tracker.

        Args:
            baseline_window_minutes: Window for calculating baseline average.
            anomaly_multiplier: Rate must exceed baseline × this value to trigger.
            min_samples: Minimum samples before anomaly detection activates.
        """
        self._window_seconds = baseline_window_minutes * 60
        self._multiplier = anomaly_multiplier
        self._min_samples = min_samples
        # IP -> list of request timestamps
        self._requests: dict[str, list[float]] = defaultdict(list)

    def record_and_check(self, ip: str, ts: Optional[float] = None) -> tuple[bool, float, float]:
        """Record a request and check if current rate is anomalous.

        Args:
            ip: Source IP address.
            ts: Event timestamp as Unix epoch. Defaults to now.

        Returns:
            Tuple of (is_anomaly, current_rate_per_min, baseline_rate_per_min).
        """
        now = ts or time.time()
        cutoff = now - self._window_seconds

        # Evict old entries
        self._requests[ip] = [t for t in self._requests[ip] if t > cutoff]

        # Record new request
        self._requests[ip].append(now)

        total = len(self._requests[ip])

        # Need minimum samples to establish baseline
        if total < self._min_samples:
            return False, 0.0, 0.0

        # Calculate baseline: avg requests per minute over the window
        time_span = max(now - self._requests[ip][0], 1.0)  # avoid div-by-zero
        baseline_rpm = (total / time_span) * 60

        # Calculate current rate: requests in the last 60 seconds
        recent_cutoff = now - 60
        recent_count = sum(1 for t in self._requests[ip] if t > recent_cutoff)
        current_rpm = float(recent_count)

        is_anomaly = current_rpm > (baseline_rpm * self._multiplier)
        return is_anomaly, current_rpm, baseline_rpm

    def reset(self) -> None:
        """Clear all baseline data."""
        self._requests.clear()


# ---------------------------------------------------------------------------
# Detection Engine
# ---------------------------------------------------------------------------
class DetectionEngine:
    """Stateful, async-safe, multi-mode detection engine.

    Combines rule-based, threshold-based, and behavioral detection.
    All configuration is loaded from config.yaml — zero hardcoded values.
    Uses asyncio.Lock for thread-safe state mutation.
    """

    def __init__(self, settings=None):
        """Initialize the detection engine with config-driven rules and thresholds.

        Args:
            settings: Optional Settings instance for dependency injection.
        """
        self._settings = settings or get_settings()
        self._lock = asyncio.Lock()

        # --- Rule-based detection ---
        self._compiled_rules: list[dict] = []
        self._compile_rules()

        # --- Threshold detection ---
        threshold_cfg = self._settings.threshold_config
        window_secs = threshold_cfg.get("window_seconds", 300)

        self._failed_login_counter = _SlidingWindowCounter(window_secs)
        self._max_failed_logins = threshold_cfg.get("max_failed_logins", 10)
        self._brute_force_severity = threshold_cfg.get("brute_force_severity", "High")

        self._scan_counter = _SlidingWindowCounter(window_secs)
        self._max_404_rate = threshold_cfg.get("max_404_rate", 50)
        self._scan_severity = threshold_cfg.get("scan_severity", "Medium")

        # --- Behavioral detection ---
        behavioral_cfg = self._settings.behavioral_config
        self._behavioral = _BehavioralBaseline(
            baseline_window_minutes=behavioral_cfg.get("baseline_window_minutes", 60),
            anomaly_multiplier=behavioral_cfg.get("anomaly_multiplier", 3.0),
            min_samples=behavioral_cfg.get("min_baseline_samples", 10),
        )
        self._anomaly_severity = behavioral_cfg.get("anomaly_severity", "Medium")

        # --- Deduplication ---
        self._dedup_window = self._settings.dedup_window
        # Key: (ip, rule_id) -> last alert timestamp
        self._dedup_cache: dict[tuple[str, str], float] = {}

        # --- Risk scoring config ---
        self._severity_weights = self._settings.risk_scoring.get("severity_weights", {})
        self._threat_intel_weight = self._settings.risk_scoring.get("threat_intel_weight", 25)
        self._frequency_weight = self._settings.risk_scoring.get("frequency_weight", 15)

        # --- Frequency tracker for risk scoring ---
        self._ip_alert_counts: dict[str, int] = defaultdict(int)

        logger.info(
            f"Detection engine initialized: {len(self._compiled_rules)} rules, "
            f"window={window_secs}s, dedup={self._dedup_window}s"
        )

    def _compile_rules(self) -> None:
        """Compile detection rules from config.yaml into regex patterns."""
        for rule in self._settings.detection_rules:
            try:
                compiled = re.compile(rule["pattern"])
                self._compiled_rules.append({
                    "rule_id": rule["rule_id"],
                    "pattern": compiled,
                    "severity": rule["severity"],
                    "description": rule["description"],
                    "weight": rule.get("weight", 10),
                })
                logger.debug(f"Compiled detection rule: {rule['rule_id']}")
            except re.error as e:
                logger.error(f"Invalid detection rule regex '{rule['rule_id']}': {e}")

    def _calculate_risk_score(
        self,
        severity: str,
        ip: str,
        threat_intel_score: float = 0.0,
    ) -> float:
        """Calculate risk score using weighted formula from config.

        Formula: severity_weight + threat_intel_score + frequency_score

        Args:
            severity: Alert severity level.
            ip: Source IP for frequency lookup.
            threat_intel_score: Score from threat intelligence (0-100).

        Returns:
            Calculated risk score as float.
        """
        # Severity weight from config
        severity_weight = self._severity_weights.get(severity, 10)

        # Threat intel contribution (weighted)
        ti_score = (threat_intel_score / 100) * self._threat_intel_weight

        # Frequency contribution: more alerts from same IP = higher score
        freq_count = self._ip_alert_counts.get(ip, 0)
        freq_score = min(freq_count * 2, self._frequency_weight)

        return round(severity_weight + ti_score + freq_score, 2)

    def _is_duplicate(self, ip: str, rule_id: str) -> bool:
        """Check if an alert is a duplicate within the dedup window.

        Suppresses repeated alerts for the same (ip, rule_id) combination
        within dedup_window_seconds.

        Args:
            ip: Source IP address.
            rule_id: Detection rule identifier.

        Returns:
            True if this is a duplicate that should be suppressed.
        """
        key = (ip, rule_id)
        now = time.time()

        if key in self._dedup_cache:
            last_alert_time = self._dedup_cache[key]
            if (now - last_alert_time) < self._dedup_window:
                return True

        # Update/create dedup entry
        self._dedup_cache[key] = now
        return False

    def _create_alert(
        self,
        ip: str,
        rule_id: str,
        severity: str,
        description: str,
        raw_event: str,
        threat_intel_score: float = 0.0,
        username: Optional[str] = None,
    ) -> Optional[Alert]:
        """Create an Alert if it's not a duplicate.

        Args:
            ip: Source IP address.
            rule_id: Detection rule that triggered.
            severity: Alert severity level.
            description: Human-readable description.
            raw_event: The raw log line or event data.
            threat_intel_score: Score from threat intelligence.
            username: Optional username for brute-force alerts.

        Returns:
            Alert object if not deduplicated, None otherwise.
        """
        # Check deduplication
        if self._is_duplicate(ip, rule_id):
            logger.debug(f"Suppressed duplicate alert: ip={ip}, rule={rule_id}")
            return None

        # Track frequency
        self._ip_alert_counts[ip] += 1

        risk_score = self._calculate_risk_score(severity, ip, threat_intel_score)

        alert = Alert(
            alert_id=str(uuid.uuid4()),
            timestamp=datetime.now(timezone.utc),
            ip=ip,
            rule_id=rule_id,
            severity=severity,
            description=description,
            raw_event=raw_event,
            risk_score=risk_score,
            username=username,
        )

        logger.info(
            f"🚨 Alert: {rule_id} | {severity} | IP={ip} | "
            f"score={risk_score} | {description[:60]}"
        )
        return alert

    async def analyze(
        self,
        event: LogEvent,
        threat_intel_score: float = 0.0,
    ) -> list[Alert]:
        """Analyze a single log event through all detection modes.

        This is the main entry point. It runs rule-based, threshold, and
        behavioral detection in sequence and returns any alerts generated.

        Uses asyncio.Lock to ensure thread-safe state mutation.

        Args:
            event: Parsed LogEvent from the log parser.
            threat_intel_score: Optional threat intel score for risk calculation.

        Returns:
            List of Alert objects generated (may be empty).
        """
        alerts: list[Alert] = []

        async with self._lock:
            # 1. Rule-based detection
            rule_alerts = self._detect_rules(event, threat_intel_score)
            alerts.extend(rule_alerts)

            # 2. Threshold detection
            threshold_alerts = self._detect_threshold(event, threat_intel_score)
            alerts.extend(threshold_alerts)

            # 3. Behavioral detection
            behavioral_alerts = self._detect_behavioral(event, threat_intel_score)
            alerts.extend(behavioral_alerts)

        return alerts

    def _detect_rules(
        self,
        event: LogEvent,
        threat_intel_score: float = 0.0,
    ) -> list[Alert]:
        """Run rule-based detection against the event URI and query string.

        Args:
            event: Parsed log event.
            threat_intel_score: Threat intelligence score.

        Returns:
            List of alerts from matching rules.
        """
        alerts = []
        # Check URI against all compiled rules
        target = event.uri  # Primary target for pattern matching

        for rule in self._compiled_rules:
            if rule["pattern"].search(target):
                alert = self._create_alert(
                    ip=event.ip,
                    rule_id=rule["rule_id"],
                    severity=rule["severity"],
                    description=rule["description"],
                    raw_event=event.raw_line,
                    threat_intel_score=threat_intel_score,
                )
                if alert is not None:
                    alerts.append(alert)

        return alerts

    def _detect_threshold(
        self,
        event: LogEvent,
        threat_intel_score: float = 0.0,
    ) -> list[Alert]:
        """Run threshold-based detection for brute-force and scanning.

        - Brute-force: Failed logins (POST to login-like URIs with 401/403).
        - Scanning: High 404 rate per IP.

        Args:
            event: Parsed log event.
            threat_intel_score: Threat intelligence score.

        Returns:
            List of threshold-triggered alerts.
        """
        alerts = []
        ts = event.timestamp.timestamp()

        # Brute-force detection: failed login attempts
        is_login_attempt = (
            event.method == "POST"
            and event.status_code in (401, 403)
            and any(kw in event.uri.lower() for kw in ["login", "auth", "signin", "session"])
        )

        if is_login_attempt:
            count = self._failed_login_counter.record(event.ip, ts)
            if count >= self._max_failed_logins:
                alert = self._create_alert(
                    ip=event.ip,
                    rule_id="BRUTE_FORCE_001",
                    severity=self._brute_force_severity,
                    description=(
                        f"Brute-force login detected: {count} failed attempts "
                        f"from {event.ip} within sliding window"
                    ),
                    raw_event=event.raw_line,
                    threat_intel_score=threat_intel_score,
                )
                if alert is not None:
                    alerts.append(alert)

        # Scanning detection: high 404 rate
        if event.status_code == 404:
            count = self._scan_counter.record(event.ip, ts)
            if count >= self._max_404_rate:
                alert = self._create_alert(
                    ip=event.ip,
                    rule_id="SCAN_001",
                    severity=self._scan_severity,
                    description=(
                        f"Path/port scanning detected: {count} 404 responses "
                        f"from {event.ip} within sliding window"
                    ),
                    raw_event=event.raw_line,
                    threat_intel_score=threat_intel_score,
                )
                if alert is not None:
                    alerts.append(alert)

        return alerts

    def _detect_behavioral(
        self,
        event: LogEvent,
        threat_intel_score: float = 0.0,
    ) -> list[Alert]:
        """Run behavioral anomaly detection based on request rate baseline.

        Flags IPs whose current request rate exceeds their baseline × multiplier.

        Args:
            event: Parsed log event.
            threat_intel_score: Threat intelligence score.

        Returns:
            List of behavioral anomaly alerts.
        """
        alerts = []
        ts = event.timestamp.timestamp()

        is_anomaly, current_rpm, baseline_rpm = self._behavioral.record_and_check(
            event.ip, ts
        )

        if is_anomaly:
            alert = self._create_alert(
                ip=event.ip,
                rule_id="ANOMALY_001",
                severity=self._anomaly_severity,
                description=(
                    f"Behavioral anomaly: {event.ip} rate {current_rpm:.1f} req/min "
                    f"exceeds baseline {baseline_rpm:.1f} req/min × multiplier"
                ),
                raw_event=event.raw_line,
                threat_intel_score=threat_intel_score,
            )
            if alert is not None:
                alerts.append(alert)

        return alerts

    async def reset(self) -> None:
        """Reset all engine state — counters, baselines, dedup cache.

        Useful for testing and periodic maintenance.
        """
        async with self._lock:
            self._failed_login_counter.reset()
            self._scan_counter.reset()
            self._behavioral.reset()
            self._dedup_cache.clear()
            self._ip_alert_counts.clear()
            logger.info("Detection engine state reset")

    @property
    def stats(self) -> dict:
        """Return engine statistics and configuration summary."""
        return {
            "rules_loaded": len(self._compiled_rules),
            "dedup_window_seconds": self._dedup_window,
            "dedup_cache_size": len(self._dedup_cache),
            "tracked_ips": len(self._ip_alert_counts),
            "total_alerts_by_ip": dict(self._ip_alert_counts),
        }
