"""DefMon database models — SQLAlchemy async ORM definitions."""

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    Enum as SAEnum,
)
from sqlalchemy.dialects.postgresql import UUID, ARRAY
from sqlalchemy.orm import DeclarativeBase, relationship
import enum


class Base(DeclarativeBase):
    """Base class for all DefMon database models."""
    pass


class SeverityLevel(str, enum.Enum):
    """Alert severity classification."""
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class IncidentStatus(str, enum.Enum):
    """Incident lifecycle status."""
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    CLOSED = "closed"


class UserRole(str, enum.Enum):
    """RBAC role definitions."""
    ADMIN = "admin"
    ANALYST = "analyst"
    VIEWER = "viewer"


def _enum_values(enum_cls: type[enum.Enum]) -> list[str]:
    """Return enum values so SQLAlchemy stores DB enum literals, not names."""
    return [member.value for member in enum_cls]


# ---------------------------------------------------------------------------
# Log Entry
# ---------------------------------------------------------------------------
class LogEntry(Base):
    """Parsed and normalized log event stored for analysis."""

    __tablename__ = "log_entries"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    ip = Column(String(45), nullable=False, index=True)  # supports IPv6
    method = Column(String(10), nullable=False)
    uri = Column(Text, nullable=False)
    status_code = Column(Integer, nullable=False)
    bytes_sent = Column(Integer, default=0)
    user_agent = Column(Text, default="")
    referrer = Column(Text, default="")
    raw_line = Column(Text, nullable=False)
    sender_id = Column(String(64), nullable=True, index=True)
    sender_name = Column(String(100), nullable=True, index=True)
    classification = Column(String(16), nullable=False, default="normal", index=True)
    is_malicious = Column(Boolean, nullable=False, default=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)


# ---------------------------------------------------------------------------
# Alert
# ---------------------------------------------------------------------------
class Alert(Base):
    """Security alert generated by the detection engine."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    alert_id = Column(UUID(as_uuid=True), default=uuid.uuid4, unique=True, nullable=False)
    timestamp = Column(DateTime, nullable=False, index=True)
    ip = Column(String(45), nullable=False, index=True)
    rule_id = Column(String(50), nullable=False, index=True)
    severity = Column(
        SAEnum(SeverityLevel, values_callable=_enum_values, name="severitylevel"),
        nullable=False,
        index=True,
    )
    description = Column(Text, nullable=False)
    raw_event = Column(Text, default="")
    risk_score = Column(Float, default=0.0)
    tags = Column(ARRAY(String), default=[])
    status = Column(String(20), default="new")
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationship
    incidents = relationship("Incident", back_populates="alert")


# ---------------------------------------------------------------------------
# Incident
# ---------------------------------------------------------------------------
class Incident(Base):
    """SOAR-generated incident linked to an alert."""

    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, autoincrement=True)
    case_id = Column(UUID(as_uuid=True), default=uuid.uuid4, unique=True, nullable=False)
    alert_id = Column(UUID(as_uuid=True), ForeignKey("alerts.alert_id"), nullable=False)
    status = Column(
        SAEnum(IncidentStatus, values_callable=_enum_values, name="incidentstatus"),
        default=IncidentStatus.OPEN,
        index=True,
    )
    severity = Column(
        SAEnum(SeverityLevel, values_callable=_enum_values, name="severitylevel"),
        nullable=False,
    )
    description = Column(Text, default="")
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    closed_at = Column(DateTime, nullable=True)

    # Relationship
    alert = relationship("Alert", back_populates="incidents")


# ---------------------------------------------------------------------------
# Blocked IP
# ---------------------------------------------------------------------------
class BlockedIP(Base):
    """IP addresses blocked by SOAR automated response."""

    __tablename__ = "blocked_ips"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ip = Column(String(45), nullable=False, unique=True, index=True)
    reason = Column(Text, default="")
    blocked_at = Column(DateTime, default=datetime.utcnow)
    blocked_by = Column(String(50), default="SOAR")


# ---------------------------------------------------------------------------
# Audit Log
# ---------------------------------------------------------------------------
class AuditLog(Base):
    """Immutable audit trail for all SOAR actions — written BEFORE execution."""

    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    action = Column(String(100), nullable=False)
    actor = Column(String(50), nullable=False, default="SOAR")
    target = Column(Text, nullable=False)
    details = Column(Text, default="")
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)


# ---------------------------------------------------------------------------
# User
# ---------------------------------------------------------------------------
class User(Base):
    """Application user with role-based access control."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(100), unique=True, nullable=False, index=True)
    hashed_password = Column(String(255), nullable=False)
    role = Column(
        SAEnum(UserRole, values_callable=_enum_values, name="userrole"),
        default=UserRole.VIEWER,
        nullable=False,
    )
    is_active = Column(Boolean, default=True)
    is_locked = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)


# ---------------------------------------------------------------------------
# Log Sender
# ---------------------------------------------------------------------------
class LogSender(Base):
    """Trusted remote log sender managed by admins."""

    __tablename__ = "log_senders"

    id = Column(String(64), primary_key=True)
    name = Column(String(100), unique=True, nullable=False, index=True)
    description = Column(Text, default="")
    api_key_hash = Column(String(128), nullable=False)
    allowed_ip = Column(String(45), nullable=True)
    is_active = Column(Boolean, default=True)
    is_blocked = Column(Boolean, default=False)
    block_reason = Column(Text, default="")
    created_by = Column(String(100), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    last_seen_at = Column(DateTime, nullable=True)
    last_log_preview = Column(Text, default="")
